In [2]:
# insurance fund adl model

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
n = 100

df = pd.DataFrame({

    "account_id": range(n),

    "symbol": np.random.choice(
        ["BTC", "ETH"],
        n
    ),

    "price": np.random.randint(
        10000,
        30000,
        n
    ),

    "position": np.random.randint(
        1,
        50,
        n
    ),

    "balance": np.random.randint(
        1000,
        20000,
        n
    ),

    "leverage": np.random.choice(
        [5, 10, 20, 50],
        n
    )

})

In [ ]:
df["notional"] = df["price"] * df["position"]

In [ ]:
df["risk_ratio"] = (
    df["notional"] / df["balance"]
)

In [ ]:
df["pnl"] = np.random.randn(len(df)) * 1000

In [ ]:
df["adl_score"] = (
    df["pnl"]
    * df["risk_ratio"]
    * df["leverage"]
)

In [ ]:
adl_queue = df.sort_values(
    "adl_score",
    ascending=False
)

adl_queue.head(10)

,account_id,symbol,price,position,balance,leverage,notional,risk_ratio,pnl,adl_score
6,6,BTC,27713,29,1661,50,803677,483.851294,1036.004175,2.506360e+07
53,53,BTC,27665,44,1548,20,1217260,786.343669,1470.690722,2.312937e+07
60,60,ETH,23572,16,1609,50,377152,234.401492,1430.084637,1.676070e+07
55,55,BTC,23147,43,19828,50,995321,50.197751,2241.116454,5.624950e+06
21,21,BTC,19460,47,12742,50,914620,71.779940,1457.658263,5.231531e+06
45,45,ETH,26657,40,12941,20,1066280,82.395487,2209.134392,3.640454e+06
39,39,BTC,17087,32,8255,50,546784,66.236705,1091.244949,3.614023e+06
86,86,BTC,29572,34,12472,50,1005448,80.616421,827.691280,3.336275e+06
15,15,ETH,16843,29,14610,50,488447,33.432375,1880.012400,3.142664e+06
97,97,BTC,25838,39,4924,20,1007682,204.647035,753.544851,3.084214e+06

In [ ]:
insurance = 1_000_000

loss = 2_000_000

adl_trigger = loss > insurance

adl_trigger

True

In [ ]:
if adl_trigger:

    print("ADL triggered")

    print(
        adl_queue.head(5)
    )

ADL triggered
    account_id symbol  price  position  balance  leverage  notional  \
6            6    BTC  27713        29     1661        50    803677
53          53    BTC  27665        44     1548        20   1217260
60          60    ETH  23572        16     1609        50    377152
55          55    BTC  23147        43    19828        50    995321
21          21    BTC  19460        47    12742        50    914620

    risk_ratio          pnl     adl_score
6   483.851294  1036.004175  2.506360e+07
53  786.343669  1470.690722  2.312937e+07
60  234.401492  1430.084637  1.676070e+07
55   50.197751  2241.116454  5.624950e+06
21   71.779940  1457.658263  5.231531e+06

In [ ]:
btc_queue = df[
    df["symbol"] == "BTC"
].sort_values(
    "adl_score",
    ascending=False
)

btc_queue.head()

,account_id,symbol,price,position,balance,leverage,notional,risk_ratio,pnl,adl_score
6,6,BTC,27713,29,1661,50,803677,483.851294,1036.004175,2.506360e+07
53,53,BTC,27665,44,1548,20,1217260,786.343669,1470.690722,2.312937e+07
55,55,BTC,23147,43,19828,50,995321,50.197751,2241.116454,5.624950e+06
21,21,BTC,19460,47,12742,50,914620,71.779940,1457.658263,5.231531e+06
39,39,BTC,17087,32,8255,50,546784,66.236705,1091.244949,3.614023e+06

In [ ]:
df["adl_rank"] = pd.qcut(
    df["adl_score"],
    5,
    labels=False
)

df.head()

,account_id,symbol,price,position,balance,leverage,notional,risk_ratio,pnl,adl_score,adl_rank
0,0,ETH,22776,9,12646,50,204984,16.209394,634.984938,514636.061243,3
1,1,BTC,26776,30,10384,20,803280,77.357473,66.847660,103423.321132,2
2,2,BTC,28322,38,7393,5,1076236,145.575003,-947.796694,-689877.534699,0
3,3,BTC,10728,11,6748,10,118008,17.487848,-109.532936,-19154.953660,1
4,4,ETH,14707,7,16170,20,102949,6.366667,756.871306,96374.946315,2

In [ ]:
print("Max score:",
      df["adl_score"].max())

print("Top ADL:",
      adl_queue.head(3))

Max score: 25063598.047222562
Top ADL:     account_id symbol  price  position  balance  leverage  notional  \
6            6    BTC  27713        29     1661        50    803677
53          53    BTC  27665        44     1548        20   1217260
60          60    ETH  23572        16     1609        50    377152

    risk_ratio          pnl     adl_score
6   483.851294  1036.004175  2.506360e+07
53  786.343669  1470.690722  2.312937e+07
60  234.401492  1430.084637  1.676070e+07